<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\search_api\Query\QueryInterface;

/**
 * Implements hook_form_FORM_ID_alter() for the search form.
 */
function custom_search_form_search_api_page_search_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $form['#submit'][] = 'custom_search_override_search_query';
}

/**
 * Submit callback to override the search query.
 */
function custom_search_override_search_query(array &$form, FormStateInterface $form_state) {
  /** @var \Drupal\search_api\Query\QueryInterface $query */
  $query = $form_state->get('search_api_query');
  if ($query instanceof QueryInterface) {
    // Modify the search query to only search for words in the title.
    $query->setFulltextFields(['title']);
  }
}
